name: Test Deploy to Bitaxe Devices

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */4 * * *'  # Check every 4 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-deploy:
    runs-on: [self-hosted, Linux, X64, ESP-Miner-device-tester-repo]
    
    steps:
    - name: Checkout test runner repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for comparing with upstream

    - name: Check upstream changes
      id: check_upstream
      if: github.event_name == 'schedule'
      run: |
        git remote add upstream https://github.com/skot/ESP-miner.git
        git fetch upstream
        if python3 check_upstream.py; then
          echo "new_commit=true" >> $GITHUB_OUTPUT
        else
          echo "new_commit=false" >> $GITHUB_OUTPUT
        fi

    - name: Setup Node.js
      if: github.event_name != 'schedule' || steps.check_upstream.outputs.new_commit == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: './ESP-miner/main/http_server/axe-os/package-lock.json'

    - name: Build web dist
      if: github.event_name != 'schedule' || steps.check_upstream.outputs.new_commit == 'true'
      working-directory: ./ESP-miner/main/http_server/axe-os
      run: |
        npm ci --prefer-offline
        npm run build --max-old-space-size=4096

    - name: esp-idf build
      if: github.event_name != 'schedule' || steps.check_upstream.outputs.new_commit == 'true'
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.3.1
        target: esp32s3
        command: |
          GITHUB_ACTIONS="true" idf.py build
        path: './ESP-miner'

    - uses: actions/setup-python@v5
      if: github.event_name != 'schedule' || steps.check_upstream.outputs.new_commit == 'true'
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Python dependencies
      if: github.event_name != 'schedule' || steps.check_upstream.outputs.new_commit == 'true'
      run: |
        pip install esptool
        pip install requests

    - name: Deploy firmware to devices
      if: github.event_name != 'schedule' || steps.check_upstream.outputs.new_commit == 'true'
      env:
        BITAXE_DEVICES: ${{ secrets.BITAXE_TEST_DEVICES }}
      run: |
        python3 deploy_firmware.py "$BITAXE_DEVICES"
